---
title: "Prior Creation"
format: html
editor: source
---

# Read in the Data

```{r}
competition <- read_csv("Competition.csv")
ends <- read_csv("Ends.csv")
games <- read_csv("Games.csv")
stones <- read_csv("Stones.csv")
competitors <- read_csv("Competitors.csv")
teams <- read_csv("Teams.csv")
```

# Stone Wrangling

```{r}
canada_stones <- stones %>% 
  filter(TeamID == 10) %>% # filter to canada
  select(CompetitionID, SessionID, GameID, EndID, TeamID, Points) %>% 
  group_by(CompetitionID, SessionID, GameID, EndID) %>% 
  summarize(any0 = ifelse(0 %in% Points, 1, 0),
            avg_points = round(mean(Points))) %>% 
  mutate(Points = case_when(
    any0 != 0 ~ 0,
    any0 == 0 ~ avg_points
  )) %>% 
  ungroup() %>% 
  select(CompetitionID, SessionID, GameID, EndID, Points)
```

# End Wrangling

```{r}
canada_ends <- ends %>% 
  filter(TeamID == 10) %>% # filter to Canada
  select(-Result, TeamID) %>% 
  mutate(PowerPlay = if_else(is.na(PowerPlay),FALSE,TRUE))
```

# Game Wrangling

```{r}
canada_games <- games %>% 
  filter((TeamID1 == 10) | (TeamID2 == 10)) %>% # filter to Canada
  mutate(CanadaWin = case_when(
    (NOC1 == "CAN") & (Winner == 1) ~ 1,
    (NOC1 != "CAN") & (Winner == 1) ~ 0,
    (NOC2 == "CAN") & (Winner == 0) ~ 1,
    (NOC2 != "CAN") & (Winner == 0) ~ 0
  )) %>% 
  select(CompetitionID, SessionID, GameID, CanadaWin)
```

# Joining the Data

```{r}
canada_curling <- competition %>% 
  select(-Place, -Venue) %>% 
  right_join(canada_games, by = join_by(CompetitionID == CompetitionID)) %>% 
  right_join(canada_ends, by = join_by(CompetitionID == CompetitionID, SessionID == SessionID, GameID == GameID)) %>% 
  left_join(canada_stones, by = join_by(CompetitionID == CompetitionID, SessionID == SessionID, GameID == GameID, EndID == EndID)) %>% 
  relocate(EndID, .after = GameID) %>% 
  group_by(CompetitionID, SessionID, GameID) %>% 
  mutate(MatchID = cur_group_id(), .after = SessionID) %>% 
  ungroup() %>% 
  select(-CompetitionID, -SessionID, -GameID, -TeamID) %>% 
  mutate(Success = ifelse((Points > 2), 1, 0))
```

# Replicate Wrangling Done to USA

```{r}
successful_powerplays_canada <- canada_curling %>% 
  # consider only powerplays
  filter(PowerPlay) %>% 
  # create a PowerPlaySuccessful variable
  mutate(PowerPlaySuccessful = if_else((Success == 1), TRUE, FALSE)) %>% 
  select(CompetitionName, MatchID, PowerPlaySuccessful)

mean(n_successful_non_powerplays_canada$SuccessfulNonPowerPlays)

n_successful_non_powerplays_canada <- canada_curling %>% 
  # consider only non powerplays
  filter(!PowerPlay) %>% 
  select(!c(PowerPlay, Points)) %>% 
  group_by(CompetitionName, MatchID) %>% 
  # count how many successful non powerplays there were per match
  summarize(SuccessfulNonPowerPlays = sum(Success) - 6)
  
final_curling_canada <- canada_curling %>% 
  select(!Success) %>% 
  group_by(CompetitionName, MatchID) %>% 
  mutate(number_of_ends = max(EndID),
         num_ends_center_6 = number_of_ends - 6) %>% 
  # pivot so there's one row per match. 
  # information about powerplay and points go to a column per end
  pivot_wider(
    names_from = "EndID",
    values_from = c("PowerPlay", "Points"),
    values_fill = list("PowerPlay" = FALSE, "Points" = 0)
  ) %>% 
  # determine if there's at least one powerplay in a match
  mutate(
    PowerPlayPresent = 
      if_else((PowerPlay_1 | PowerPlay_2 | PowerPlay_3 | PowerPlay_4 | 
                 PowerPlay_5 | PowerPlay_6 | PowerPlay_7 | PowerPlay_8 | 
                 PowerPlay_9), TRUE, FALSE)
  ) %>% 
  # add on information regarding successful powerplays
  left_join(successful_powerplays_canada, 
            by = join_by("CompetitionName" == "CompetitionName", 
                         "MatchID" == "MatchID")) %>% 
  # add on information regarding number of successful non powerplays
  left_join(n_successful_non_powerplays_canada, 
            by = join_by("CompetitionName" == "CompetitionName", 
                         "MatchID" == "MatchID")) %>% 
  # turn NA values from lack of powerplay in match to FALSE, 
  # create index for competition name
  mutate(PowerPlaySuccessful = 
           if_else(is.na(PowerPlaySuccessful), FALSE, PowerPlaySuccessful),
         CompetitionIndex = case_when(
           CompetitionName == "Beijing 2022 Olympic Winter Games" ~ 1,
           CompetitionName == "World Mixed Doubles Curling Championship 2023" ~ 2,
           CompetitionName == "World Mixed Doubles Curling Championship 2024" ~ 3,
           CompetitionName == "World Mixed Doubles Curling Championship 2025" ~ 4
         ))
```

```{r}
final_curling_canada %>% 
  ungroup() %>% 
  summarize_at(vars(starts_with("PowerPlay_")), mean)
```


# Calculate Priors for Question 1

```{r}
# calculation for beta_0
final_curling_canada %>% 
  filter(num_ends_center_6 == 0,
         !PowerPlayPresent)

# calculation for beta_1 
final_curling_canada %>% 
  filter(PowerPlay_5)

final_curling_canada %>% 
  ungroup() %>% 
  filter(!PowerPlay_5) %>% 
  summarize(prop_victory = mean(CanadaWin))

# calculation for beta_2 
final_curling_canada %>% 
  ungroup() %>% 
  filter(PowerPlay_6) %>% 
  summarize(prop_victory = mean(CanadaWin))

final_curling_canada %>% 
  ungroup() %>% 
  filter(!PowerPlay_6) %>% 
  summarize(prop_victory = mean(CanadaWin))

# calculation for beta_3 
final_curling_canada %>% 
  ungroup() %>% 
  filter(PowerPlay_7) %>% 
  summarize(prop_victory = mean(CanadaWin))

final_curling_canada %>% 
  ungroup() %>% 
  filter(!PowerPlay_7) %>% 
  summarize(prop_victory = mean(CanadaWin))

# calculation for beta_4
final_curling_canada %>% 
  ungroup() %>% 
  filter(PowerPlay_8) %>% 
  summarize(prop_victory = mean(CanadaWin))

final_curling_canada %>% 
  ungroup() %>% 
  filter(!PowerPlay_8) %>% 
  summarize(prop_victory = mean(CanadaWin))

# calculation for beta_5
final_curling_canada %>% 
  ggplot(aes(x = number_of_ends, fill = factor(CanadaWin))) +
  geom_bar(position = "fill")

 final_curling_canada %>% 
  ungroup() %>% 
  group_by(number_of_ends) %>% 
  summarize(prop_victory = mean(CanadaWin))
```
# Calculating Priors for Q2 - Betas 1:4 are all pre-calced by Bridget thanks Bridget!
```{r}
#B0 
final_curling_canada %>% 
    filter(PowerPlaySuccessful == F && SuccessfulNonPowerPlays == 0)

#B5
final_curling_canada %>% 
    filter(PowerPlaySuccessful == T)
#22/41 = 0.54


#B6
mean(final_curling_canada$SuccessfulNonPowerPlays)
```


